services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot_work_or_study
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  data:
